//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemP1.adonetdatamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
