//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemP1.adonetdatamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationInfo
    {
        public int Id { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string CollegeName { get; set; }
        public string BoardName { get; set; }
        public string MajorSubject { get; set; }
        public string PassedYear { get; set; }
        public string Grade { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual StudentLevel StudentLevel { get; set; }
    }
}
