//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemP1.adonetdatamodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSP1Entities : DbContext
    {
        public SMSP1Entities()
            : base("name=SMSP1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseDetail> CourseDetails { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EducationInfo> EducationInfoes { get; set; }
        public virtual DbSet<Muncipality> Muncipalities { get; set; }
        public virtual DbSet<ParentDetail> ParentDetails { get; set; }
        public virtual DbSet<ParentRelationship> ParentRelationships { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<StudentLevel> StudentLevels { get; set; }
    }
}
