//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemP1.adonetdatamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentDetail
    {
        public int ParentId { get; set; }
        public string ParentName { get; set; }
        public string ParentPhone { get; set; }
        public int Relationship { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual ParentRelationship ParentRelationship { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
